spring.datasource:
  # https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters
  url: jdbc:postgresql://localhost:5432/postgres?connectTimeout=10&socketTimeout=40
  username: postgres
  password: "password1"
  driverClassName: org.postgresql.Driver
